name: shadowsocks
version: 2.8.2-1
summary: A fast tunnel proxy that helps you bypass firewalls
description: A fast tunnel proxy that helps you bypass firewalls
icon: shadowsocks.png

apps:
  sslocal:
    command: usr/bin/sslocal
    uses: [listener-service]

  ssserver:
    command: usr/bin/ssserver
    uses: [listener-service]

uses:
  listener-service:
    type: migration-skill
    caps: [network-service]

parts:
  shadowsocks:
    plugin: python2
    source: ./2.8.2-snappy.tar.gz
