name: shadowsocks
version: 2.9.1+20181219
summary: A fast tunnel proxy that helps you bypass "Firewalls"
description: |
  A fast tunnel proxy that helps you bypass "Firewalls".

  This is the Python version.
confinement: strict
icon: shadowsocks-256px.png
grade: stable
base: core20
source-code: https://github.com/anthonywong/shadowsocks-snap

apps:
  sslocal:
    command: bin/sslocal
    plugs: [network, network-bind]

  ssserver:
    command: bin/ssserver
    plugs: [network, network-bind]

parts:
  shadowsocks:
    plugin: python
    source: https://github.com/shadowsocks/shadowsocks.git
    source-branch: master
    source-depth: 1
    stage-packages:
      - libsodium23
    override-pull: |
      snapcraftctl pull
      patch -p0 < ../../../patches/01-fix_find_library.patch
    filesets:
      exclude-files:
        - -usr/share/applications
        - -usr/share/bug
        - -usr/share/doc
        - -usr/share/man
        - -usr/share/dh-python
        - -usr/share/lintian
        - -usr/share/debhelper
    stage:
      - $exclude-files
    override-build: |
      snapcraftctl build
      install -m 444 -D $SNAPCRAFT_PART_BUILD/debian/ssserver.1 $SNAPCRAFT_PART_INSTALL/share/man/man1/ssserver.1
      install -m 444 -D $SNAPCRAFT_PART_BUILD/debian/sslocal.1 $SNAPCRAFT_PART_INSTALL/share/man/man1/sslocal.1
      install -m 444 -D $SNAPCRAFT_PART_BUILD/debian/config.json $SNAPCRAFT_PART_INSTALL/etc/config.json
