name: shadowsocks
version: 2.9.1+20181219
summary: A fast tunnel proxy that helps you bypass "Firewalls"
description: |
  A fast tunnel proxy that helps you bypass "Firewalls".

  This is the Python version.
confinement: strict
icon: shadowsocks-256px.png
grade: stable

apps:
  sslocal:
    command: bin/sslocal
    plugs: [network, network-bind]

  ssserver:
    command: bin/ssserver
    plugs: [network, network-bind]

parts:
  shadowsocks:
    plugin: python
    python-version: python3
    source: https://github.com/shadowsocks/shadowsocks.git
    source-branch: master
    source-depth: 1
    stage-packages:
      - libsodium18
    override-pull: |
      snapcraftctl pull
      patch -p0 < ../../../patches/01-fix_find_library.patch
    override-build: |
      snapcraftctl build
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/applications
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bug
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/man
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/dh-python
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/lintian
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/debhelper
      install -m 444 -D $SNAPCRAFT_PART_BUILD/debian/ssserver.1 $SNAPCRAFT_PART_INSTALL/usr/share/man/man1/ssserver.1
      install -m 444 -D $SNAPCRAFT_PART_BUILD/debian/sslocal.1 $SNAPCRAFT_PART_INSTALL/usr/share/man/man1/sslocal.1
      install -m 444 -D $SNAPCRAFT_PART_BUILD/debian/config.json $SNAPCRAFT_PART_INSTALL/etc/config.json
