name: shadowsocks
version: 2.8.2-2
summary: A fast tunnel proxy that helps you bypass firewalls
description: A fast tunnel proxy that helps you bypass firewalls

apps:
  sslocal:
    command: usr/bin/sslocal
    plugs: [network, network-bind]

  ssserver:
    command: usr/bin/ssserver
    plugs: [network, network-bind]

parts:
  shadowsocks:
    plugin: python2
    source: ./2.8.2-snappy.tar.gz
