name: shadowsocks
version: 2.9.1+git
summary: A fast tunnel proxy that helps you bypass firewalls
description: A fast tunnel proxy that helps you bypass firewalls
confinement: strict
icon: shadowsocks-256px.png
grade: stable

apps:
  sslocal:
    command: bin/sslocal
    plugs: [network, network-bind]

  ssserver:
    command: bin/ssserver
    plugs: [network, network-bind]

parts:
  stage-patch: 
    plugin: dump
    source: ./patch

  shadowsocks:
    after: [stage-patch]
    plugin: python
    python-version: python3
    source: https://github.com/shadowsocks/shadowsocks.git
    source-branch: master
    stage-packages:
        - libsodium18
        - libdb5.3
    override-pull: |
        snapcraftctl pull
        patch -p0 < $SNAPCRAFT_STAGE/01-fix_find_library.patch

