name: shadowsocks
version: 2.9.1+git
summary: A fast tunnel proxy that helps you bypass firewalls
description: A fast tunnel proxy that helps you bypass firewalls
confinement: strict
icon: shadowsocks-256px.png
grade: stable

apps:
  sslocal:
    command: bin/sslocal
    plugs: [network, network-bind]

  ssserver:
    command: bin/ssserver
    plugs: [network, network-bind]

parts:
  shadowsocks:
    plugin: python
    python-version: python3
    source: https://github.com/shadowsocks/shadowsocks.git
    source-branch: master
    stage-packages:
        - libsodium18

